encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),

    path("wiki/<str:atitle>", views.display_entry, name="entry"),

    path("create/", views.create_new_page, name="create"),
    path("save/", views.save_page, name="save"),

    path("edit/<str:atitle>", views.edit_page, name="edit"),
    path("savechanges/<str:atitle>", views.save_edit, name="save_edit"),

    path("random/", views.random_page, name="random"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.core.exceptions import ValidationError
from . import util
import markdown2
from random import choice

class NewSearchForm(forms.Form):
    query = forms.CharField(label="Search Encyclopedia...")
class NewTitleForm(forms.Form):
    title = forms.CharField(label="Enter title:")

def index(request):
    if request.method == "POST":
        form = NewSearchForm(request.POST)
        # Check if form data is valid (server-side)
        if form.is_valid():
            # Isolate the query from the 'cleaned' version of form data
            query = form.cleaned_data["query"]

            # Look if the query corresponds to an existing entry
            if query in util.list_entries():
                return render(request, "encyclopedia/entry.html", {
                    "form": NewSearchForm(),
                    "entry": markdown2.markdown(util.get_entry(query)),
                    "atitle": query})

            matching = []
            for entry in util.list_entries():
                if query in entry:
                    matching.append(entry)
                else:
                    continue

            # If the query is a substring of an existing entry title
            if matching:
                return render(request, "encyclopedia/search_results.html", {
                    "form": NewSearchForm(),
                    "atitle": query,
                    "matching": matching})
        else:
            # If the form is invalid, re-render the page with existing information.
            return render(request, "encyclopedia/index.html", {
                "form": form
            })

    return render(request, "encyclopedia/index.html", {
        "form": NewSearchForm(),
        "entries": util.list_entries(),
        })


def display_entry(request, atitle):
    # Look if the query corresponds to an existing entry
    if (atitle in util.list_entries()):
        return render(request, "encyclopedia/entry.html", {
        "form": NewSearchForm(),
        "entry": markdown2.markdown(util.get_entry(atitle)),
        "atitle": atitle})
    else:
        return render(request, "encyclopedia/error.html", {
            "form": NewSearchForm(),
            "atitle": atitle})

def create_new_page(request):
    return render(request, "encyclopedia/create.html", {
        "form": NewSearchForm(),
        "titleform": NewTitleForm(),
    })

def save_page(request):
    if request.method == "POST":
        title = request.POST["title"]
        content = request.POST["content"]
        if title not in util.list_entries():
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("wiki:entry", args=(title,)))
        else:
            return render(request, "encyclopedia/create.html", {
                "form": NewSearchForm(),
                "titleform": NewTitleForm(),
                "title": title,
                "content": content,
                "error_message":
                    "<b>Error</b> : an entry with your chosen title already exists; Please enter a new one.",
            })
    else:
        return HttpResponseRedirect(reverse("wiki:create"))

def edit_page(request, atitle):
    return render(request, "encyclopedia/edit.html", {
        "form": NewSearchForm(),
        "atitle": atitle,
        "content": util.get_entry(atitle),
    })

def save_edit(request, atitle):
    if request.method == "POST":
        content = request.POST["content"]
        util.save_entry(atitle, content)
        return HttpResponseRedirect(reverse("wiki:entry", args=(atitle,)))

def random_page(request):
    random_entry = ''.join([choice(util.list_entries())])
    return render(request, "encyclopedia/entry.html", {
        "form": NewSearchForm(),
        "entry": markdown2.markdown(util.get_entry(random_entry)),
        "atitle": random_entry})

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>Create</h1>

    <form action="{% url 'wiki:save' %}" method="POST" id="pageform">

        {% csrf_token %}

        <br>

        {{ titleform }}
        {{ error_message|safe }}

        <br><br>

        <label for="content">Enter Description:</label>

        <div style="text-align: center">
            <input type="submit" value="Save">
        </div>

        <br>

    </form>

        <textarea id="content" name="content" rows="4" cols="50" form="pageform">{{ content }}</textarea>
{% endblock %}


encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ atitle }}
{% endblock %}

{% block body %}
    <h1>Edit: {{ atitle }}</h1>

    <form action="{% url 'wiki:save_edit' atitle %}" method="POST" id="pageform">

        {% csrf_token %}

        <label for="content">Enter Description:</label>

        <div style="text-align: center">
            <input type="submit" value="Save changes">
        </div>

        <br>

    </form>

        <textarea id="content" name="content" rows="4" cols="50" form="pageform">{{ content }}</textarea>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ atitle }}
{% endblock %}

{% block body %}
    {{ entry|safe  }}
    <div>
        <a href="{% url 'wiki:edit' atitle %}">Edit Page</a>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Not Found : {{ atitle }}
{% endblock %}

{% block body %}
    <h1 style="text-align: center">Error 404</h1>
    <br>
    <ul>
    <li>The page corresponding to "<b>{{ atitle }}</b>" does not presently exist in the encyclopedia</li>
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                    <form action="{% url 'wiki:index' %}" method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <input type="submit">
                    </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ atitle }}
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for match in matching %}
            <li><a href="wiki/{{ match }}">{{ match }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}